version: "3.9"
   
services:

  redis:
    image: redis
    restart: always

  db:
    image: postgres:14-alpine
    container_name: db-1
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres

        
  api:
    restart: always
    build: .
    volumes:
     - .:/code/  
    command: bash -c "sleep 30 && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"

      
  web:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend


  celery:
    build:
      context: .
    command: bash -c "sleep 30 && celery -A google_sheets_api worker -l info"
    restart: always
    volumes:
     - .:/code/  


  celery-beat:
    build:
      context: .
    command: bash -c "sleep 30 && celery -A google_sheets_api beat -l info"
    restart: always
    volumes:
     - .:/code/  
