# Generated by Django 4.1.7 on 2023-03-16 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='price',
            new_name='price_rub',
        ),
        migrations.AddField(
            model_name='order',
            name='price_usd',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
