# Generated by Django 4.1.7 on 2023-03-16 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_rename_price_order_price_rub_order_price_usd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='price_rub',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='price_usd',
            field=models.FloatField(),
        ),
    ]
