# Generated by Django 4.1.7 on 2023-03-16 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_alter_order_price_rub_alter_order_price_usd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='price_usd',
            field=models.IntegerField(),
        ),
    ]
