# Generated by Django 4.1.7 on 2023-03-18 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_exchangerate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exchangerate',
            old_name='value',
            new_name='rate',
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='exchange',
            field=models.CharField(default=0, max_length=55),
            preserve_default=False,
        ),
    ]
